theme: jekyll-theme-cayman
<<<<<<< HEAD
title: "Introducción a R para Ciencias Sociales. Aplicación practica en la EPH"
description: "Materiales del curso"
=======
title: "R en FLACSO 2019"
description: "Curso de R para Ciencias Sociales. Aplicación practica en la EPH"
>>>>>>> df956c40714111c76196bf4df301ea9bb3fa1987
show_downloads: "true"
