theme: jekyll-theme-cayman
title: "Introducción a R para Ciencias Sociales. Aplicación practica en la EPH"
description: "Materiales del curso"
title: "R en FLACSO 2019"
description: "Curso de R para Ciencias Sociales. Aplicación practica en la EPH"
show_downloads: "true"
